export const CHECKMARK1 = 'CHECKMARK1';
export const CHECKMARK2 = 'CHECKMARK2';
export const CHECKMARK3 = 'CHECKMARK3';
export const CHECKMARK4 = 'CHECKMARK4';
export const RESET_CHECKMARKS = 'RESET_CHECKMARKS';

export const CHANGE_PLAY = 'CHANGE_PLAY';
export const DECREASE_TIMER = 'DECREASE_TIMER';
export const RESET_TIMER = 'RESET_TIMER';
export const SHORT_BREAK_MODE = 'SHORT_BREAK_MODE';
export const LONG_BREAK_MODE = 'LONG_BREAK_MODE';
export const TIMER_MODE = 'TIMER_MODE';

export const CHANGE_PLAY_SHORT_BREAK = 'CHANGE_PLAY_SHORT_BREAK';
export const DECREASE_TIMER_SHORT_BREAK = 'DECREASE_TIMER_SHORT_BREAK';
export const RESET_TIMER_SHORT_BREAK = 'RESET_TIMER_SHORT_BREAK';

export const CHANGE_PLAY_LONG_BREAK = 'CHANGE_PLAY_LONG_BREAK';
export const DECREASE_TIMER_LONG_BREAK = 'DECREASE_TIMER_LONG_BREAK';
export const RESET_TIMER_LONG_BREAK = 'RESET_TIMER_LONG_BREAK';

export const ACTIVATE_ALARM = 'ACTIVATE_ALARM';
export const CANCEL_ALARM = 'CANCEL_ALARM';
